Ys llama pebblo integration
yograjopcito/llama_index pull request #1
Opened 2024-03-22 10:21 UTC by yograjopcito

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Version Bump?

Did I bump the version in the `pyproject.toml` file of the package I am updating? (Except for the `llama-index-core` package)

- [ ] Yes
- [ ] No

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Added new unit/integration tests
- [ ] Added new notebook (that tests end-to-end)
- [ ] I stared at the code and made sure it makes sense

## Suggested Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added Google Colab support for the newly added notebooks.
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I ran `make format; make lint` to appease the lint gods

2024-04-15 18:39 UTC, rahul-trip commented on llama-index-integrations/readers/llama-index-readers-pebblo/tests/test_readers_pebblo.py
> +    assert BaseReader.__name__ in names_of_base_classes
Should we add a basic test case, to be able to read a local file (for eg a json or csv file) ?

2024-04-15 18:42 UTC, rahul-trip commented on llama-index-integrations/readers/llama-index-readers-pebblo/llama_index/readers/pebblo/base.py
> +        return self.docs
Should we also implement its counterpart, lazy_load_data() ?

2024-04-15 18:44 UTC, rahul-trip commented on llama-index-integrations/readers/llama-index-readers-pebblo/llama_index/readers/pebblo/base.py
> +        """
Please confirm if we should include integration with Pebblo_Cloud in this initial version.

2024-04-15 19:05 UTC, rahul-trip commented on llama-index-integrations/readers/llama-index-readers-pebblo/llama_index/readers/pebblo/base.py
> +                doc_source_path = get_full_path(str(kwargs.get("file")))
What if input argument is not present in `file` keyword. IMO, it can be a url or `input_file` (json) etc.

2024-04-15 19:06 UTC, rahul-trip commented on llama-index-integrations/readers/llama-index-readers-pebblo/llama_index/readers/pebblo/utility.py
> +            location = loader_dict["file_path"]
We should add more possible `source input keys` for example, `file` and `input_file` etc.

2024-04-15 19:07 UTC, rahul-trip commented on llama-index-integrations/readers/llama-index-readers-pebblo/llama_index/readers/pebblo/base.py
> +                doc_source_path = get_full_path(str(kwargs.get("file")))
Instead of kwargs.get("file"), IMO its better to use `self.source_path` directly in this case.

2024-04-15 19:11 UTC, rahul-trip requested changes
Please feel free to ask, if some comment is unclear.

2024-04-16 14:20 UTC, shreyas-damle commented on llama-index-integrations/readers/llama-index-readers-pebblo/llama_index/readers/pebblo/base.py
> +        """
Pebblo cloud integration won't be needed at this time. That would be follow on feature.

2024-04-17 07:45 UTC, shisodeyograj commented on llama-index-integrations/readers/llama-index-readers-pebblo/tests/test_readers_pebblo.py
> +    assert BaseReader.__name__ in names_of_base_classes
We can but we need to add some CSV or PDF file for test somewhere in the repo. I'm not sure about llama-index standard to add such files for test cases. So we have just included the basic standard test case. Almost all the readers in llama-readers has this single test case only.

2024-04-17 07:47 UTC, yograjopcito commented on llama-index-integrations/readers/llama-index-readers-pebblo/llama_index/readers/pebblo/base.py
> +        return self.docs
No llama-index reader has implemented lazy_load_data() apart from mongoDB and couchDB readers.

2024-04-17 09:11 UTC, yograjopcito commented on llama-index-integrations/readers/llama-index-readers-pebblo/llama_index/readers/pebblo/base.py
> +                doc_source_path = get_full_path(str(kwargs.get("file")))
Added input_file. For url not sure about how to compute the content size(source_path_size). For now we are planning to support following text based readers only
- CSVReader
- PDFReader
- DocxReader
- SimpleDirectoryReader

2024-04-17 09:13 UTC, yograjopcito commented on llama-index-integrations/readers/llama-index-readers-pebblo/llama_index/readers/pebblo/utility.py
> +            location = loader_dict["file_path"]
Removed path, file_path(Langchain file souces) and added input_dir, file, input_file(Llama file sources).

2024-04-22 10:46 UTC, rahul-trip commented on llama-index-integrations/readers/llama-index-readers-pebblo/tests/test_readers_pebblo.py
> +    assert BaseReader.__name__ in names_of_base_classes
Yeah right, saw that. Please add a super small csv/json file within our test directory. Shouldn't be be a problem.

2024-04-22 10:47 UTC, rahul-trip commented on llama-index-integrations/readers/llama-index-readers-pebblo/llama_index/readers/pebblo/base.py
> +        return self.docs
It is not there today, but will be there in future. Lets take it up in future PRs. :)

2024-04-24 10:46 UTC, rahul-trip commented on llama-index-integrations/readers/llama-index-readers-pebblo/llama_index/readers/pebblo/base.py
> +                doc_source_path = get_full_path(str(kwargs.get("file")))
So we are just supporting above 4 loaders as of now?

2024-04-26 17:18 UTC, merged